version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "4321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: SchedulerData
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build: .
    ports: 
      - "5000:5000"
    depends_on:
      - db
  migration:
    build: .
    command: npm run migration
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
  seed:
    build: .
    command: npx knex seed:run
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
volumes: 
  data: 
